remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Louis Langholtz
description: website + blog.
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
