# Use remote_theme to get master/latest of the minima theme!
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
title: Louis Langholtz @ GitHub.IO
url: https://louis-langholtz.github.io
description: "Welcome to my GitHub Pages! Here you'll find info on my publicly available software related: events, presentations, projects and more."
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
footer-links:
  github: louis-langholtz
date_format: "%b %-d, %Y"
defaults:
  - scope:
      path: "image"
    values:
      image: true
  - scope:
      path: "presentation"
    values:
      presentation: true
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/louis-langholtz"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/7410358/louis-langholtz"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/louis-langholtz"
disqus:
  shortname: https-louis-langholtz-github-io
