# Use remote_theme to get master/latest of the minima theme!
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
title: Louis Langholtz
description: website + blog.
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
footer-links:
  github: louis-langholtz
date_format: "%b %-d, %Y"
defaults:
  - scope:
      path: "image"
    values:
      image: true
  - scope:
      path: "presentation"
    values:
      presentation: true
github_username: louis-langholtz
minima:
  social_links:
    - platform: github
      user_url: "https://github.com/louis-langholtz"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/7410358/louis-langholtz"
author:
disqus:
  shortname: https-louis-langholtz-github-io.disqus.com
