remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
title: Louis Langholtz
description: website + blog.
lsi: false
safe: true
incremental: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
footer-links:
  github: louis-langholtz
date_format: "%b %-d, %Y"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/pdf"
    values:
      presentation: true
